server:
  port: 8082
  servlet:
    context-path: /stream
management:
  endpoints:
    web:
      exposure:
        include: health
spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
#spring:
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#logging:
#  level:
#    root: DEBUG